default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: inventario_pai
  username: postgres
  password: mariana80

test:
  <<: *default
  database: inventario_pai

production:
  adapter: postgresql
  pool: 5
  encoding: unicode
  database: inventario_pai
